/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package salestaxesproblem;

import salestaxesproblem.domain.Basket;
import salestaxesproblem.domain.ProductType;
import salestaxesproblem.taxes.BasicSalesTax;
import salestaxesproblem.taxes.ImportDutyTax;
import salestaxesproblem.taxes.SimpleTaxingService;
import salestaxesproblem.taxes.TaxingService;

import java.util.EnumSet;

public class App {

    public static void main(String[] args) {
        if (args.length <= 0) {
            System.out.println("No arguments are passed! Pass basket input file to start.");
        } else {
            TaxingService taxingService = new SimpleTaxingService();
            taxingService.addTax(new ImportDutyTax(.05f));
            taxingService.addTax(new BasicSalesTax(EnumSet.of(ProductType.OTHER), .1f));
            ReceiptPrinter receiptPrinter = new ReceiptPrinter();
            BasketInputParser parser = new BasketInputParser();
            for (String input : args) {
                Basket basket = parser.createBasketFromFile(input, taxingService, receiptPrinter);
                basket.printReceipt();
                System.out.println();
            }
        }
    }
}
